In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv(r'D:\TUFEL\Data scientist pro\Machine Learinng\Projects\Logistic Regression (Titanic)\documents (2)\ML Project - Logistic Regression Titanic Survival U16955478860.txt')

# 1.print all the column names

In [3]:
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
pd.DataFrame(df.columns)

              0
0   PassengerId
1      Survived
2        Pclass
3          Name
4           Sex
5           Age
6         SibSp
7         Parch
8        Ticket
9          Fare
10        Cabin
11     Embarked

# 3) describe the data

In [5]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# 4) check the null value

In [6]:
df.isnull().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

# 5) if there are Null values, Handle these

## Age

We have null values in age column so we will replace them by median

In [7]:
df['Age'].fillna(df['Age'].median(),inplace=True)

In [8]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

## Cabin

In [9]:
df['Cabin'].isnull()

0       True
1      False
2       True
3      False
4       True
       ...
886     True
887    False
888     True
889    False
890     True
Name: Cabin, Length: 891, dtype: bool

In [10]:
round(df['Cabin'].isnull().sum()/len(df)*100)

77

Here in Cabin column we have null Values more than 70% so we will drop that column

In [11]:
df.drop('Cabin',axis=1,inplace=True)

In [12]:
df.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,S

# Embarked

In [13]:
df['Embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

So, here we can se "Embarked" is a categorical table so first we will find mode

In [14]:
df['Embarked'].mode()

0    S
Name: Embarked, dtype: object

We will fill this column with 'S'

In [15]:
df['Embarked'].fillna(df['Embarked'].mode()[0],inplace=True)

In [16]:
df['Embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

## Now we will Check for null values

In [17]:
df.isnull().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age            False
SibSp          False
Parch          False
Ticket         False
Fare           False
Embarked       False
dtype: bool

In [22]:
df['Survived'].unique()

array([0, 1])

In [27]:
a={0:'Not Survived',
   1:'Survived'}

In [29]:
df['Survived'].replace(a,inplace=True)

In [30]:
df['Survived']

0      Not Survived
1          Survived
2          Survived
3          Survived
4      Not Survived
           ...
886    Not Survived
887        Survived
888    Not Survived
889        Survived
890    Not Survived
Name: Survived, Length: 891, dtype: object

In [31]:
pwd

'C:\\Users\\Admin\\Desktop'